### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by s-gv** [Qatja/qatja-android#3]
Is this library open source? On jcenter?

**Comment by lohnn** [comment]
In the source code of QatjaService.java you can see that the project (or at least that class) is under Apache 2.0 license.
You find the project on bintray, easily downloadable with gradle from [here](https://bintray.com/wetcat/Qatja/qatja-android/), as clearly shown under **[Installation](https://github.com/Qatja/qatja-android#installation)** header in README.

Regarding how to use it in code, I'm still working on figuring it all out ;)

**Comment by agoransson** [comment]
It's still a little bit in "beta", I need to clean up the documentation.

The project is on jcenter as @lohnn pointed out, you should be able to download it with `compile 'se.wetcat.qatja:qatja-android:0.1.9'`. And the whole project is under Apache 2.0, including the [core](https://github.com/Qatja/core) classes this library relies on.

When you've added the gradle import then you can declare the service in your manifest, and bind to it from some Android component. In my example I choose to bind from a base activity.

```xml
<service
    android:name="se.wetcat.qatja.android.QatjaService"
    android:exported="false"/>
```

Create the service connection.

```java
private QatjaService client;

private ServiceConnection connection = new ServiceConnection() {
  @Override
  public void onServiceConnected(ComponentName name, IBinder binder) {
    client = ((QatjaBinder) binder).getService();
    isBound = true;
    
    mqtt.setHandler(mHandler);
  }

  @Override
  public void onServiceDisconnected(ComponentName name) {
    isBound = false;
  }
};
```

Then you can use the `client` object to connect and publish messages to the broker.

I've published a working example in [https://github.com/Qatja/Android-Example](https://github.com/Qatja/Android-Example). Most of the connection logic is handled in the [ConnectionActivity](https://github.com/Qatja/Android-Example/blob/master/app/src/main/java/se/wetcat/qatja/androidexample/ConnectionActivity.java)

**Comment by 1heReactor** [comment]
I can't see service running in android settings, while using servicebind. Should it be like that? So far, my app stops to recieve any inc messages from broker like in 10min, if phone is locked...
I want to start it from MainActivity and run in background for a long time:
I've set 
```

   @Override
    protected void onStop() {
        super.onStop();

       // unbindService(connection);
    }
```



_Sent from my Meizu m3 note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by agoransson** [comment]
@1heReactor I believe the problem you've encountered is because of an overly complicated implementation of the Keep Alive timer. I've since then simplified it, and will when I'm comfortable with it release a new version. It will be available during this week. I'll close this issue when it has been made available on jcenter.

Sorry for the delay.
